package com.arudra.crm.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * A dedicated, admin-approved attendance terminal (Android device + external fingerprint scanner).
 *
 * Security: the device authenticates with a high-entropy secret issued once after approval; only its
 * SHA-256 {@link #credentialHash} is stored. The device exchanges the secret for a short-lived device
 * token whose {@code cv} claim must equal {@link #credentialVersion} — revoking or blocking bumps the
 * version / changes the status, so every outstanding token stops working on the next request.
 *
 * Status is one of {@link AttendanceDeviceStatus}. OFFLINE is not stored: it is derived for display
 * from {@link #lastSeenAt} so an ACTIVE device that lost connectivity can still sync when it returns.
 */
@Getter
@Setter
@Entity
@Table(name = "attendance_devices")
public class AttendanceDevice extends BaseEntity {

    @Column(name = "device_name", nullable = false, length = 120)
    private String deviceName;

    /** Human-friendly unique id shown on the terminal and in the admin list, e.g. ARUDRA-ATT-0001. */
    @Column(name = "device_code", nullable = false, unique = true, length = 60)
    private String deviceCode;

    /** Install-scoped UUID generated by the terminal app on first start. Null for an unpaired slot. */
    @Column(name = "device_uuid", unique = true, length = 64)
    private String deviceUuid;

    @Column(nullable = false, length = 20)
    private String status = AttendanceDeviceStatus.PENDING;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "branch_id")
    private Branch branch;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "location_id")
    private AttendanceLocation location;

    @JsonIgnore
    @Column(name = "credential_hash", length = 128)
    private String credentialHash;

    @JsonIgnore
    @Column(name = "credential_version", nullable = false)
    private Integer credentialVersion = 0;

    @Column(name = "credential_issued_at")
    private LocalDateTime credentialIssuedAt;

    @JsonIgnore
    @Column(name = "credential_delivered", nullable = false)
    private Boolean credentialDelivered = false;

    @JsonIgnore
    @Column(name = "poll_token_hash", length = 128)
    private String pollTokenHash;

    @JsonIgnore
    @Column(name = "pairing_code_hash", length = 128)
    private String pairingCodeHash;

    @Column(name = "pairing_expires_at")
    private LocalDateTime pairingExpiresAt;

    @Column(name = "app_version", length = 40)
    private String appVersion;

    /** CONNECTED | DISCONNECTED | PERMISSION_DENIED | ERROR | UNKNOWN — as last reported. */
    @Column(name = "scanner_status", length = 30)
    private String scannerStatus;

    @Column(name = "scanner_vendor", length = 60)
    private String scannerVendor;

    @Column(name = "scanner_model", length = 100)
    private String scannerModel;

    @Column(name = "scanner_serial", length = 100)
    private String scannerSerial;

    @Column(length = 100)
    private String manufacturer;

    @Column(length = 100)
    private String model;

    @Column(name = "os_version", length = 40)
    private String osVersion;

    @Column(name = "last_ip", length = 64)
    private String lastIp;

    @Column(name = "last_seen_at")
    private LocalDateTime lastSeenAt;

    @Column(name = "last_sync_at")
    private LocalDateTime lastSyncAt;

    @Column(name = "pending_sync_count", nullable = false)
    private Integer pendingSyncCount = 0;

    @JsonIgnore
    @Column(name = "offline_alert_sent", nullable = false)
    private Boolean offlineAlertSent = false;

    @Column(name = "registered_at")
    private LocalDateTime registeredAt;

    @Column(name = "approved_by", length = 255)
    private String approvedBy;

    @Column(name = "approved_at")
    private LocalDateTime approvedAt;

    @Column(name = "status_reason", length = 255)
    private String statusReason;

    @Column(name = "status_changed_by", length = 255)
    private String statusChangedBy;

    @Column(name = "status_changed_at")
    private LocalDateTime statusChangedAt;
}
