-- JB Decor real product catalog (65 rows from scripts/catalog/jb-decor-catalog.csv).
-- GENERATED by scripts/catalog/generate-catalog-migration.mjs — edit the CSV and regenerate, don't hand-edit.
-- Additive + idempotent: every insert is skipped when the slug already exists, so content later edited
-- from the CRM Website module is never overwritten. Images live at https://jbdecorcdm.com/catalog/<sku>-NN.jpg
-- (website/public/catalog). Prices stay 0 — the public site is enquiry-only and never shows them.

-- ── Categories ──
INSERT INTO shop_categories (created_at, updated_at, created_by, version, is_deleted, name, slug, icon, display_order, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Netlon (Mosquito Nets)', 'netlon-mosquito-nets', 'ShieldCheck', 1, b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_categories WHERE slug = 'netlon-mosquito-nets');
INSERT INTO shop_categories (created_at, updated_at, created_by, version, is_deleted, name, slug, icon, display_order, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Curtains', 'curtains', 'Blinds', 2, b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_categories WHERE slug = 'curtains');
INSERT INTO shop_categories (created_at, updated_at, created_by, version, is_deleted, name, slug, icon, display_order, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Blinds', 'blinds', 'Layers', 3, b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_categories WHERE slug = 'blinds');
INSERT INTO shop_categories (created_at, updated_at, created_by, version, is_deleted, name, slug, icon, display_order, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Curtain Rods & Accessories', 'curtain-rods-accessories', 'Wrench', 4, b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_categories WHERE slug = 'curtain-rods-accessories');
INSERT INTO shop_categories (created_at, updated_at, created_by, version, is_deleted, name, slug, icon, display_order, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Mats & Flooring', 'mats-flooring', 'Palette', 5, b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_categories WHERE slug = 'mats-flooring');
INSERT INTO shop_categories (created_at, updated_at, created_by, version, is_deleted, name, slug, icon, display_order, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Wall Decor', 'wall-decor', 'Wallpaper', 6, b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_categories WHERE slug = 'wall-decor');
INSERT INTO shop_categories (created_at, updated_at, created_by, version, is_deleted, name, slug, icon, display_order, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Interior Works', 'interior-works', 'CookingPot', 7, b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_categories WHERE slug = 'interior-works');
INSERT INTO shop_categories (created_at, updated_at, created_by, version, is_deleted, name, slug, icon, display_order, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Home Decor', 'home-decor', 'Flower2', 8, b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_categories WHERE slug = 'home-decor');

-- ── Products ──
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Mosquito Net - Door Type', 'mosquito-net-door-type', 'NET-DOOR',
  (SELECT id FROM shop_categories WHERE slug = 'netlon-mosquito-nets' AND is_deleted = b'0' LIMIT 1),
  'Hinged mosquito-net door fitted to your existing door frame. Keeps insects out while letting air and light in.', 'Hinged mosquito-net door fitted to your existing door frame. Keeps insects out while letting air and light in.', 'https://jbdecorcdm.com/catalog/net-door-01.jpg', '["https://jbdecorcdm.com/catalog/net-door-01.jpg","https://jbdecorcdm.com/catalog/net-door-02.jpg","https://jbdecorcdm.com/catalog/net-door-03.jpg","https://jbdecorcdm.com/catalog/net-door-04.jpg","https://jbdecorcdm.com/catalog/net-door-05.jpg","https://jbdecorcdm.com/catalog/net-door-06.jpg","https://jbdecorcdm.com/catalog/net-door-07.jpg","https://jbdecorcdm.com/catalog/net-door-08.jpg","https://jbdecorcdm.com/catalog/net-door-09.jpg","https://jbdecorcdm.com/catalog/net-door-10.jpg"]',
  '[{"label":"Category","value":"Netlon (Mosquito Nets)"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"NET-DOOR"}]', 0, 0, 0, 0, b'1', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'mosquito-net-door-type');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Mosquito Net - Main Door Type', 'mosquito-net-main-door-type', 'NET-MAINDOOR',
  (SELECT id FROM shop_categories WHERE slug = 'netlon-mosquito-nets' AND is_deleted = b'0' LIMIT 1),
  'Heavy-duty mosquito-net door for main entrances, with a sturdy frame built for daily use.', 'Heavy-duty mosquito-net door for main entrances, with a sturdy frame built for daily use.', 'https://jbdecorcdm.com/catalog/net-maindoor-01.jpg', '["https://jbdecorcdm.com/catalog/net-maindoor-01.jpg","https://jbdecorcdm.com/catalog/net-maindoor-02.jpg","https://jbdecorcdm.com/catalog/net-maindoor-03.jpg","https://jbdecorcdm.com/catalog/net-maindoor-04.jpg","https://jbdecorcdm.com/catalog/net-maindoor-05.jpg","https://jbdecorcdm.com/catalog/net-maindoor-06.jpg","https://jbdecorcdm.com/catalog/net-maindoor-07.jpg","https://jbdecorcdm.com/catalog/net-maindoor-08.jpg","https://jbdecorcdm.com/catalog/net-maindoor-09.jpg","https://jbdecorcdm.com/catalog/net-maindoor-10.jpg"]',
  '[{"label":"Category","value":"Netlon (Mosquito Nets)"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"NET-MAINDOOR"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'mosquito-net-main-door-type');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Mosquito Net - Velcro Type', 'mosquito-net-velcro-type', 'NET-VELCRO',
  (SELECT id FROM shop_categories WHERE slug = 'netlon-mosquito-nets' AND is_deleted = b'0' LIMIT 1),
  'Budget-friendly window mosquito net fixed with Velcro tape. Easy to remove and wash; no drilling needed.', 'Budget-friendly window mosquito net fixed with Velcro tape. Easy to remove and wash; no drilling needed.', 'https://jbdecorcdm.com/catalog/net-velcro-01.jpg', '["https://jbdecorcdm.com/catalog/net-velcro-01.jpg","https://jbdecorcdm.com/catalog/net-velcro-02.jpg","https://jbdecorcdm.com/catalog/net-velcro-03.jpg","https://jbdecorcdm.com/catalog/net-velcro-04.jpg","https://jbdecorcdm.com/catalog/net-velcro-05.jpg","https://jbdecorcdm.com/catalog/net-velcro-06.jpg","https://jbdecorcdm.com/catalog/net-velcro-07.jpg","https://jbdecorcdm.com/catalog/net-velcro-08.jpg","https://jbdecorcdm.com/catalog/net-velcro-09.jpg","https://jbdecorcdm.com/catalog/net-velcro-10.jpg"]',
  '[{"label":"Category","value":"Netlon (Mosquito Nets)"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"NET-VELCRO"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'mosquito-net-velcro-type');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Pleated Mosquito Net', 'pleated-mosquito-net', 'NET-PLEATED',
  (SELECT id FROM shop_categories WHERE slug = 'netlon-mosquito-nets' AND is_deleted = b'0' LIMIT 1),
  'Pleated (plisse) mosquito screen that folds neatly to the side. Ideal for wide doors and balconies.', 'Pleated (plisse) mosquito screen that folds neatly to the side. Ideal for wide doors and balconies.', 'https://jbdecorcdm.com/catalog/net-pleated-01.jpg', '["https://jbdecorcdm.com/catalog/net-pleated-01.jpg","https://jbdecorcdm.com/catalog/net-pleated-02.jpg","https://jbdecorcdm.com/catalog/net-pleated-03.jpg","https://jbdecorcdm.com/catalog/net-pleated-04.jpg","https://jbdecorcdm.com/catalog/net-pleated-05.jpg"]',
  '[{"label":"Category","value":"Netlon (Mosquito Nets)"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"NET-PLEATED"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'pleated-mosquito-net');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Sliding Mosquito Net', 'sliding-mosquito-net', 'NET-SLIDING',
  (SELECT id FROM shop_categories WHERE slug = 'netlon-mosquito-nets' AND is_deleted = b'0' LIMIT 1),
  'Aluminium-frame sliding mosquito net for sliding windows and doors. Smooth, long-lasting operation.', 'Aluminium-frame sliding mosquito net for sliding windows and doors. Smooth, long-lasting operation.', 'https://jbdecorcdm.com/catalog/net-sliding-01.jpg', '["https://jbdecorcdm.com/catalog/net-sliding-01.jpg","https://jbdecorcdm.com/catalog/net-sliding-02.jpg","https://jbdecorcdm.com/catalog/net-sliding-03.jpg"]',
  '[{"label":"Category","value":"Netlon (Mosquito Nets)"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"NET-SLIDING"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'sliding-mosquito-net');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Door Net', 'door-net', 'NET-DOORNET',
  (SELECT id FROM shop_categories WHERE slug = 'netlon-mosquito-nets' AND is_deleted = b'0' LIMIT 1),
  'Custom-sized door mesh for kitchens, balconies and utility doors.', 'Custom-sized door mesh for kitchens, balconies and utility doors.', 'https://jbdecorcdm.com/catalog/net-doornet-01.jpg', '["https://jbdecorcdm.com/catalog/net-doornet-01.jpg","https://jbdecorcdm.com/catalog/net-doornet-02.jpg","https://jbdecorcdm.com/catalog/net-doornet-03.jpg","https://jbdecorcdm.com/catalog/net-doornet-04.jpg","https://jbdecorcdm.com/catalog/net-doornet-05.jpg","https://jbdecorcdm.com/catalog/net-doornet-06.jpg","https://jbdecorcdm.com/catalog/net-doornet-07.jpg","https://jbdecorcdm.com/catalog/net-doornet-08.jpg","https://jbdecorcdm.com/catalog/net-doornet-09.jpg"]',
  '[{"label":"Category","value":"Netlon (Mosquito Nets)"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"NET-DOORNET"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'door-net');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Folding Net', 'folding-net', 'NET-FOLDING',
  (SELECT id FROM shop_categories WHERE slug = 'netlon-mosquito-nets' AND is_deleted = b'0' LIMIT 1),
  'Foldable tent-style mosquito net for beds. Pops up in seconds and folds flat for storage and travel.', 'Foldable tent-style mosquito net for beds. Pops up in seconds and folds flat for storage and travel.', 'https://jbdecorcdm.com/catalog/net-folding-01.jpg', '["https://jbdecorcdm.com/catalog/net-folding-01.jpg","https://jbdecorcdm.com/catalog/net-folding-02.jpg","https://jbdecorcdm.com/catalog/net-folding-03.jpg","https://jbdecorcdm.com/catalog/net-folding-04.jpg","https://jbdecorcdm.com/catalog/net-folding-05.jpg","https://jbdecorcdm.com/catalog/net-folding-06.jpg","https://jbdecorcdm.com/catalog/net-folding-07.jpg","https://jbdecorcdm.com/catalog/net-folding-08.jpg","https://jbdecorcdm.com/catalog/net-folding-09.jpg"]',
  '[{"label":"Category","value":"Netlon (Mosquito Nets)"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"NET-FOLDING"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'folding-net');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Hanging Net', 'hanging-net', 'NET-HANGING',
  (SELECT id FROM shop_categories WHERE slug = 'netlon-mosquito-nets' AND is_deleted = b'0' LIMIT 1),
  'Ceiling-hung mosquito net canopy for single and double beds.', 'Ceiling-hung mosquito net canopy for single and double beds.', 'https://jbdecorcdm.com/catalog/net-hanging-01.jpg', '["https://jbdecorcdm.com/catalog/net-hanging-01.jpg","https://jbdecorcdm.com/catalog/net-hanging-02.jpg","https://jbdecorcdm.com/catalog/net-hanging-03.jpg","https://jbdecorcdm.com/catalog/net-hanging-04.jpg","https://jbdecorcdm.com/catalog/net-hanging-05.jpg"]',
  '[{"label":"Category","value":"Netlon (Mosquito Nets)"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"NET-HANGING"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'hanging-net');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Readymade Curtains', 'readymade-curtains', 'CUR-READY',
  (SELECT id FROM shop_categories WHERE slug = 'curtains' AND is_deleted = b'0' LIMIT 1),
  'Ready-to-hang curtains in popular sizes, colours and styles, including eyelet, pleated and swag designs.', 'Ready-to-hang curtains in popular sizes, colours and styles, including eyelet, pleated and swag designs.', 'https://jbdecorcdm.com/catalog/cur-ready-01.jpg', '["https://jbdecorcdm.com/catalog/cur-ready-01.jpg","https://jbdecorcdm.com/catalog/cur-ready-02.jpg","https://jbdecorcdm.com/catalog/cur-ready-03.jpg","https://jbdecorcdm.com/catalog/cur-ready-04.jpg","https://jbdecorcdm.com/catalog/cur-ready-05.jpg","https://jbdecorcdm.com/catalog/cur-ready-06.jpg","https://jbdecorcdm.com/catalog/cur-ready-07.jpg","https://jbdecorcdm.com/catalog/cur-ready-08.jpg","https://jbdecorcdm.com/catalog/cur-ready-09.jpg","https://jbdecorcdm.com/catalog/cur-ready-10.jpg"]',
  '[{"label":"Category","value":"Curtains"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"CUR-READY"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'readymade-curtains');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Customized Curtains', 'customized-curtains', 'CUR-CUSTOM',
  (SELECT id FROM shop_categories WHERE slug = 'curtains' AND is_deleted = b'0' LIMIT 1),
  'Curtains designed, stitched and fitted to your exact window size and style.', 'Curtains designed, stitched and fitted to your exact window size and style.', 'https://jbdecorcdm.com/catalog/cur-custom-01.jpg', '["https://jbdecorcdm.com/catalog/cur-custom-01.jpg","https://jbdecorcdm.com/catalog/cur-custom-02.jpg","https://jbdecorcdm.com/catalog/cur-custom-03.jpg","https://jbdecorcdm.com/catalog/cur-custom-04.jpg","https://jbdecorcdm.com/catalog/cur-custom-05.jpg","https://jbdecorcdm.com/catalog/cur-custom-06.jpg","https://jbdecorcdm.com/catalog/cur-custom-07.jpg","https://jbdecorcdm.com/catalog/cur-custom-08.jpg","https://jbdecorcdm.com/catalog/cur-custom-09.jpg","https://jbdecorcdm.com/catalog/cur-custom-10.jpg"]',
  '[{"label":"Category","value":"Curtains"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"CUR-CUSTOM"}]', 0, 0, 0, 0, b'1', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'customized-curtains');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Curtain Cloth', 'curtain-cloth', 'CUR-CLOTH',
  (SELECT id FROM shop_categories WHERE slug = 'curtains' AND is_deleted = b'0' LIMIT 1),
  'Wide range of curtain fabrics: blackout, sheer, printed, velvet and more, sold by the metre.', 'Wide range of curtain fabrics: blackout, sheer, printed, velvet and more, sold by the metre.', 'https://jbdecorcdm.com/catalog/cur-cloth-01.jpg', '["https://jbdecorcdm.com/catalog/cur-cloth-01.jpg","https://jbdecorcdm.com/catalog/cur-cloth-02.jpg","https://jbdecorcdm.com/catalog/cur-cloth-03.jpg","https://jbdecorcdm.com/catalog/cur-cloth-04.jpg","https://jbdecorcdm.com/catalog/cur-cloth-05.jpg","https://jbdecorcdm.com/catalog/cur-cloth-06.jpg","https://jbdecorcdm.com/catalog/cur-cloth-07.jpg"]',
  '[{"label":"Category","value":"Curtains"},{"label":"Sold by","value":"meter"},{"label":"Product code","value":"CUR-CLOTH"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'curtain-cloth');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Curtain Stitching', 'curtain-stitching', 'CUR-STITCH',
  (SELECT id FROM shop_categories WHERE slug = 'curtains' AND is_deleted = b'0' LIMIT 1),
  'Professional curtain stitching: eyelet, pleated, ripple-fold and more, using your fabric or ours.', 'Professional curtain stitching: eyelet, pleated, ripple-fold and more, using your fabric or ours.', 'https://jbdecorcdm.com/catalog/cur-stitch-01.jpg', '["https://jbdecorcdm.com/catalog/cur-stitch-01.jpg","https://jbdecorcdm.com/catalog/cur-stitch-02.jpg"]',
  '[{"label":"Category","value":"Curtains"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"CUR-STITCH"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'curtain-stitching');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Curtain Cloth Rolls', 'curtain-cloth-rolls', 'CUR-ROLL',
  (SELECT id FROM shop_categories WHERE slug = 'curtains' AND is_deleted = b'0' LIMIT 1),
  'Curtain fabric in full rolls for dealers, contractors and bulk projects.', 'Curtain fabric in full rolls for dealers, contractors and bulk projects.', NULL, NULL,
  '[{"label":"Category","value":"Curtains"},{"label":"Sold by","value":"roll"},{"label":"Product code","value":"CUR-ROLL"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'curtain-cloth-rolls');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'God Screen Curtains', 'god-screen-curtains', 'CUR-GOD',
  (SELECT id FROM shop_categories WHERE slug = 'curtains' AND is_deleted = b'0' LIMIT 1),
  'Printed devotional curtains for pooja rooms and temple doorways.', 'Printed devotional curtains for pooja rooms and temple doorways.', 'https://jbdecorcdm.com/catalog/cur-god-01.jpg', '["https://jbdecorcdm.com/catalog/cur-god-01.jpg","https://jbdecorcdm.com/catalog/cur-god-02.jpg","https://jbdecorcdm.com/catalog/cur-god-03.jpg","https://jbdecorcdm.com/catalog/cur-god-04.jpg","https://jbdecorcdm.com/catalog/cur-god-05.jpg","https://jbdecorcdm.com/catalog/cur-god-06.jpg","https://jbdecorcdm.com/catalog/cur-god-07.jpg","https://jbdecorcdm.com/catalog/cur-god-08.jpg"]',
  '[{"label":"Category","value":"Curtains"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"CUR-GOD"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'god-screen-curtains');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Hospital Curtains', 'hospital-curtains', 'CUR-HOSPITAL',
  (SELECT id FROM shop_categories WHERE slug = 'curtains' AND is_deleted = b'0' LIMIT 1),
  'Hospital cubicle curtains with ceiling tracks for wards, ICUs and clinics. Easy to clean and replace.', 'Hospital cubicle curtains with ceiling tracks for wards, ICUs and clinics. Easy to clean and replace.', 'https://jbdecorcdm.com/catalog/cur-hospital-01.jpg', '["https://jbdecorcdm.com/catalog/cur-hospital-01.jpg","https://jbdecorcdm.com/catalog/cur-hospital-02.jpg","https://jbdecorcdm.com/catalog/cur-hospital-03.jpg","https://jbdecorcdm.com/catalog/cur-hospital-04.jpg","https://jbdecorcdm.com/catalog/cur-hospital-05.jpg","https://jbdecorcdm.com/catalog/cur-hospital-06.jpg","https://jbdecorcdm.com/catalog/cur-hospital-07.jpg","https://jbdecorcdm.com/catalog/cur-hospital-08.jpg","https://jbdecorcdm.com/catalog/cur-hospital-09.jpg","https://jbdecorcdm.com/catalog/cur-hospital-10.jpg"]',
  '[{"label":"Category","value":"Curtains"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"CUR-HOSPITAL"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'hospital-curtains');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Stage Curtains', 'stage-curtains', 'CUR-STAGE',
  (SELECT id FROM shop_categories WHERE slug = 'curtains' AND is_deleted = b'0' LIMIT 1),
  'Auditorium and stage curtains, including motorised options, for schools, halls and theatres.', 'Auditorium and stage curtains, including motorised options, for schools, halls and theatres.', 'https://jbdecorcdm.com/catalog/cur-stage-01.jpg', '["https://jbdecorcdm.com/catalog/cur-stage-01.jpg","https://jbdecorcdm.com/catalog/cur-stage-02.jpg","https://jbdecorcdm.com/catalog/cur-stage-03.jpg"]',
  '[{"label":"Category","value":"Curtains"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"CUR-STAGE"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'stage-curtains');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Remote Control Curtains', 'remote-control-curtains', 'CUR-REMOTE',
  (SELECT id FROM shop_categories WHERE slug = 'curtains' AND is_deleted = b'0' LIMIT 1),
  'Motorised curtains that open and close with a remote or smartphone.', 'Motorised curtains that open and close with a remote or smartphone.', NULL, NULL,
  '[{"label":"Category","value":"Curtains"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"CUR-REMOTE"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'remote-control-curtains');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Zebra Blinds', 'zebra-blinds', 'BL-ZEBRA',
  (SELECT id FROM shop_categories WHERE slug = 'blinds' AND is_deleted = b'0' LIMIT 1),
  'Dual-layer zebra (day-and-night) blinds that let you control light with alternating sheer and solid bands.', 'Dual-layer zebra (day-and-night) blinds that let you control light with alternating sheer and solid bands.', 'https://jbdecorcdm.com/catalog/bl-zebra-01.jpg', '["https://jbdecorcdm.com/catalog/bl-zebra-01.jpg","https://jbdecorcdm.com/catalog/bl-zebra-02.jpg","https://jbdecorcdm.com/catalog/bl-zebra-03.jpg","https://jbdecorcdm.com/catalog/bl-zebra-04.jpg","https://jbdecorcdm.com/catalog/bl-zebra-05.jpg","https://jbdecorcdm.com/catalog/bl-zebra-06.jpg"]',
  '[{"label":"Category","value":"Blinds"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"BL-ZEBRA"}]', 0, 0, 0, 0, b'1', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'zebra-blinds');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Wooden Blinds', 'wooden-blinds', 'BL-WOODEN',
  (SELECT id FROM shop_categories WHERE slug = 'blinds' AND is_deleted = b'0' LIMIT 1),
  'Natural wooden slat blinds that add warmth and elegance to living rooms, bedrooms and offices.', 'Natural wooden slat blinds that add warmth and elegance to living rooms, bedrooms and offices.', 'https://jbdecorcdm.com/catalog/bl-wooden-01.jpg', '["https://jbdecorcdm.com/catalog/bl-wooden-01.jpg","https://jbdecorcdm.com/catalog/bl-wooden-02.jpg","https://jbdecorcdm.com/catalog/bl-wooden-03.jpg","https://jbdecorcdm.com/catalog/bl-wooden-04.jpg","https://jbdecorcdm.com/catalog/bl-wooden-05.jpg","https://jbdecorcdm.com/catalog/bl-wooden-06.jpg","https://jbdecorcdm.com/catalog/bl-wooden-07.jpg","https://jbdecorcdm.com/catalog/bl-wooden-08.jpg","https://jbdecorcdm.com/catalog/bl-wooden-09.jpg","https://jbdecorcdm.com/catalog/bl-wooden-10.jpg"]',
  '[{"label":"Category","value":"Blinds"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"BL-WOODEN"}]', 0, 0, 0, 0, b'1', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'wooden-blinds');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'PVC Blinds', 'pvc-blinds', 'BL-PVC',
  (SELECT id FROM shop_categories WHERE slug = 'blinds' AND is_deleted = b'0' LIMIT 1),
  'Durable, water-resistant PVC blinds for balconies, kitchens and outdoor areas.', 'Durable, water-resistant PVC blinds for balconies, kitchens and outdoor areas.', 'https://jbdecorcdm.com/catalog/bl-pvc-01.jpg', '["https://jbdecorcdm.com/catalog/bl-pvc-01.jpg","https://jbdecorcdm.com/catalog/bl-pvc-02.jpg","https://jbdecorcdm.com/catalog/bl-pvc-03.jpg","https://jbdecorcdm.com/catalog/bl-pvc-04.jpg","https://jbdecorcdm.com/catalog/bl-pvc-05.jpg"]',
  '[{"label":"Category","value":"Blinds"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"BL-PVC"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'pvc-blinds');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Roller Blinds', 'roller-blinds', 'BL-ROLLER',
  (SELECT id FROM shop_categories WHERE slug = 'blinds' AND is_deleted = b'0' LIMIT 1),
  'Simple, clean roller blinds in blackout and sunscreen fabrics.', 'Simple, clean roller blinds in blackout and sunscreen fabrics.', NULL, NULL,
  '[{"label":"Category","value":"Blinds"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"BL-ROLLER"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'roller-blinds');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Roman Blinds', 'roman-blinds', 'BL-ROMAN',
  (SELECT id FROM shop_categories WHERE slug = 'blinds' AND is_deleted = b'0' LIMIT 1),
  'Fabric Roman blinds that fold into soft, elegant pleats when raised.', 'Fabric Roman blinds that fold into soft, elegant pleats when raised.', 'https://jbdecorcdm.com/catalog/bl-roman-01.jpg', '["https://jbdecorcdm.com/catalog/bl-roman-01.jpg","https://jbdecorcdm.com/catalog/bl-roman-02.jpg","https://jbdecorcdm.com/catalog/bl-roman-03.jpg","https://jbdecorcdm.com/catalog/bl-roman-04.jpg","https://jbdecorcdm.com/catalog/bl-roman-05.jpg"]',
  '[{"label":"Category","value":"Blinds"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"BL-ROMAN"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'roman-blinds');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Vertical Blinds', 'vertical-blinds', 'BL-VERTICAL',
  (SELECT id FROM shop_categories WHERE slug = 'blinds' AND is_deleted = b'0' LIMIT 1),
  'Vertical blinds for wide windows and sliding doors. Ideal for offices.', 'Vertical blinds for wide windows and sliding doors. Ideal for offices.', 'https://jbdecorcdm.com/catalog/bl-vertical-01.jpg', '["https://jbdecorcdm.com/catalog/bl-vertical-01.jpg","https://jbdecorcdm.com/catalog/bl-vertical-02.jpg","https://jbdecorcdm.com/catalog/bl-vertical-03.jpg","https://jbdecorcdm.com/catalog/bl-vertical-04.jpg","https://jbdecorcdm.com/catalog/bl-vertical-05.jpg"]',
  '[{"label":"Category","value":"Blinds"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"BL-VERTICAL"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'vertical-blinds');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Venetian Blinds', 'venetian-blinds', 'BL-VENETIAN',
  (SELECT id FROM shop_categories WHERE slug = 'blinds' AND is_deleted = b'0' LIMIT 1),
  'Aluminium Venetian blinds with adjustable slats for precise light control.', 'Aluminium Venetian blinds with adjustable slats for precise light control.', 'https://jbdecorcdm.com/catalog/bl-venetian-01.jpg', '["https://jbdecorcdm.com/catalog/bl-venetian-01.jpg","https://jbdecorcdm.com/catalog/bl-venetian-02.jpg","https://jbdecorcdm.com/catalog/bl-venetian-03.jpg","https://jbdecorcdm.com/catalog/bl-venetian-04.jpg","https://jbdecorcdm.com/catalog/bl-venetian-05.jpg"]',
  '[{"label":"Category","value":"Blinds"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"BL-VENETIAN"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'venetian-blinds');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Customized Printed Blinds', 'customized-printed-blinds', 'BL-PRINTED',
  (SELECT id FROM shop_categories WHERE slug = 'blinds' AND is_deleted = b'0' LIMIT 1),
  'Blinds printed with your own photo, logo or design. Great for homes, shops and offices.', 'Blinds printed with your own photo, logo or design. Great for homes, shops and offices.', 'https://jbdecorcdm.com/catalog/bl-printed-01.jpg', '["https://jbdecorcdm.com/catalog/bl-printed-01.jpg","https://jbdecorcdm.com/catalog/bl-printed-02.jpg","https://jbdecorcdm.com/catalog/bl-printed-03.jpg","https://jbdecorcdm.com/catalog/bl-printed-04.jpg","https://jbdecorcdm.com/catalog/bl-printed-05.jpg","https://jbdecorcdm.com/catalog/bl-printed-06.jpg","https://jbdecorcdm.com/catalog/bl-printed-07.jpg","https://jbdecorcdm.com/catalog/bl-printed-08.jpg"]',
  '[{"label":"Category","value":"Blinds"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"BL-PRINTED"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'customized-printed-blinds');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Remote Control Blinds', 'remote-control-blinds', 'BL-REMOTE',
  (SELECT id FROM shop_categories WHERE slug = 'blinds' AND is_deleted = b'0' LIMIT 1),
  'Motorised blinds operated by remote or smartphone.', 'Motorised blinds operated by remote or smartphone.', NULL, NULL,
  '[{"label":"Category","value":"Blinds"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"BL-REMOTE"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'remote-control-blinds');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'SS Curtain Rods & Pipes', 'ss-curtain-rods-pipes', 'ROD-SS',
  (SELECT id FROM shop_categories WHERE slug = 'curtain-rods-accessories' AND is_deleted = b'0' LIMIT 1),
  'Stainless-steel curtain rods and pipes in multiple diameters and finishes. Rust-free and long-lasting.', 'Stainless-steel curtain rods and pipes in multiple diameters and finishes. Rust-free and long-lasting.', 'https://jbdecorcdm.com/catalog/rod-ss-01.jpg', '["https://jbdecorcdm.com/catalog/rod-ss-01.jpg","https://jbdecorcdm.com/catalog/rod-ss-02.jpg","https://jbdecorcdm.com/catalog/rod-ss-03.jpg","https://jbdecorcdm.com/catalog/rod-ss-04.jpg"]',
  '[{"label":"Category","value":"Curtain Rods & Accessories"},{"label":"Sold by","value":"feet"},{"label":"Product code","value":"ROD-SS"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'ss-curtain-rods-pipes');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Curtain Rod Holders', 'curtain-rod-holders', 'ROD-HOLDER',
  (SELECT id FROM shop_categories WHERE slug = 'curtain-rods-accessories' AND is_deleted = b'0' LIMIT 1),
  'Wall and ceiling brackets for curtain rods in steel, brass and decorative designs.', 'Wall and ceiling brackets for curtain rods in steel, brass and decorative designs.', 'https://jbdecorcdm.com/catalog/rod-holder-01.jpg', '["https://jbdecorcdm.com/catalog/rod-holder-01.jpg","https://jbdecorcdm.com/catalog/rod-holder-02.jpg","https://jbdecorcdm.com/catalog/rod-holder-03.jpg","https://jbdecorcdm.com/catalog/rod-holder-04.jpg","https://jbdecorcdm.com/catalog/rod-holder-05.jpg","https://jbdecorcdm.com/catalog/rod-holder-06.jpg","https://jbdecorcdm.com/catalog/rod-holder-07.jpg","https://jbdecorcdm.com/catalog/rod-holder-08.jpg","https://jbdecorcdm.com/catalog/rod-holder-09.jpg"]',
  '[{"label":"Category","value":"Curtain Rods & Accessories"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"ROD-HOLDER"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'curtain-rod-holders');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Curtain Rod Finials', 'curtain-rod-finials', 'ROD-FINIAL',
  (SELECT id FROM shop_categories WHERE slug = 'curtain-rods-accessories' AND is_deleted = b'0' LIMIT 1),
  'Decorative end caps for curtain rods: crystal, steel, floral and classic styles.', 'Decorative end caps for curtain rods: crystal, steel, floral and classic styles.', 'https://jbdecorcdm.com/catalog/rod-finial-01.jpg', '["https://jbdecorcdm.com/catalog/rod-finial-01.jpg","https://jbdecorcdm.com/catalog/rod-finial-02.jpg","https://jbdecorcdm.com/catalog/rod-finial-03.jpg","https://jbdecorcdm.com/catalog/rod-finial-04.jpg","https://jbdecorcdm.com/catalog/rod-finial-05.jpg","https://jbdecorcdm.com/catalog/rod-finial-06.jpg","https://jbdecorcdm.com/catalog/rod-finial-07.jpg","https://jbdecorcdm.com/catalog/rod-finial-08.jpg","https://jbdecorcdm.com/catalog/rod-finial-09.jpg","https://jbdecorcdm.com/catalog/rod-finial-10.jpg"]',
  '[{"label":"Category","value":"Curtain Rods & Accessories"},{"label":"Sold by","value":"pair"},{"label":"Product code","value":"ROD-FINIAL"}]', 0, 0, 0, 0, b'1', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'curtain-rod-finials');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Curtain Tracks', 'curtain-tracks', 'ROD-TRACK',
  (SELECT id FROM shop_categories WHERE slug = 'curtain-rods-accessories' AND is_deleted = b'0' LIMIT 1),
  'Aluminium curtain tracks, including ripple-fold (S-wave) systems, for smooth gliding curtains.', 'Aluminium curtain tracks, including ripple-fold (S-wave) systems, for smooth gliding curtains.', 'https://jbdecorcdm.com/catalog/rod-track-01.jpg', '["https://jbdecorcdm.com/catalog/rod-track-01.jpg","https://jbdecorcdm.com/catalog/rod-track-02.jpg","https://jbdecorcdm.com/catalog/rod-track-03.jpg","https://jbdecorcdm.com/catalog/rod-track-04.jpg"]',
  '[{"label":"Category","value":"Curtain Rods & Accessories"},{"label":"Sold by","value":"feet"},{"label":"Product code","value":"ROD-TRACK"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'curtain-tracks');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Curtain Hooks & Rings', 'curtain-hooks-rings', 'ROD-HOOK',
  (SELECT id FROM shop_categories WHERE slug = 'curtain-rods-accessories' AND is_deleted = b'0' LIMIT 1),
  'Curtain hooks, rings and runners for every rod and track type.', 'Curtain hooks, rings and runners for every rod and track type.', 'https://jbdecorcdm.com/catalog/rod-hook-01.jpg', '["https://jbdecorcdm.com/catalog/rod-hook-01.jpg","https://jbdecorcdm.com/catalog/rod-hook-02.jpg","https://jbdecorcdm.com/catalog/rod-hook-03.jpg","https://jbdecorcdm.com/catalog/rod-hook-04.jpg","https://jbdecorcdm.com/catalog/rod-hook-05.jpg"]',
  '[{"label":"Category","value":"Curtain Rods & Accessories"},{"label":"Sold by","value":"pack"},{"label":"Product code","value":"ROD-HOOK"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'curtain-hooks-rings');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Curtain Springs', 'curtain-springs', 'ROD-SPRING',
  (SELECT id FROM shop_categories WHERE slug = 'curtain-rods-accessories' AND is_deleted = b'0' LIMIT 1),
  'Spring wire curtain rods for small windows, cabinets and light curtains.', 'Spring wire curtain rods for small windows, cabinets and light curtains.', 'https://jbdecorcdm.com/catalog/rod-spring-01.jpg', '["https://jbdecorcdm.com/catalog/rod-spring-01.jpg","https://jbdecorcdm.com/catalog/rod-spring-02.jpg","https://jbdecorcdm.com/catalog/rod-spring-03.jpg"]',
  '[{"label":"Category","value":"Curtain Rods & Accessories"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"ROD-SPRING"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'curtain-springs');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Curtain & Blind Accessories', 'curtain-blind-accessories', 'ROD-ACC',
  (SELECT id FROM shop_categories WHERE slug = 'curtain-rods-accessories' AND is_deleted = b'0' LIMIT 1),
  'Eyelet rings and tape, blind spare parts, roller-blind kits, hook-and-loop tape and curtain canvas.', 'Eyelet rings and tape, blind spare parts, roller-blind kits, hook-and-loop tape and curtain canvas.', 'https://jbdecorcdm.com/catalog/rod-acc-01.jpg', '["https://jbdecorcdm.com/catalog/rod-acc-01.jpg","https://jbdecorcdm.com/catalog/rod-acc-02.jpg","https://jbdecorcdm.com/catalog/rod-acc-03.jpg","https://jbdecorcdm.com/catalog/rod-acc-04.jpg","https://jbdecorcdm.com/catalog/rod-acc-05.jpg","https://jbdecorcdm.com/catalog/rod-acc-06.jpg","https://jbdecorcdm.com/catalog/rod-acc-07.jpg","https://jbdecorcdm.com/catalog/rod-acc-08.jpg","https://jbdecorcdm.com/catalog/rod-acc-09.jpg","https://jbdecorcdm.com/catalog/rod-acc-10.jpg"]',
  '[{"label":"Category","value":"Curtain Rods & Accessories"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"ROD-ACC"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'curtain-blind-accessories');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Vinyl Flooring', 'vinyl-flooring', 'MAT-VINYL',
  (SELECT id FROM shop_categories WHERE slug = 'mats-flooring' AND is_deleted = b'0' LIMIT 1),
  'Waterproof vinyl flooring rolls and planks. Easy to install and maintain.', 'Waterproof vinyl flooring rolls and planks. Easy to install and maintain.', 'https://jbdecorcdm.com/catalog/mat-vinyl-01.jpg', '["https://jbdecorcdm.com/catalog/mat-vinyl-01.jpg","https://jbdecorcdm.com/catalog/mat-vinyl-02.jpg","https://jbdecorcdm.com/catalog/mat-vinyl-03.jpg","https://jbdecorcdm.com/catalog/mat-vinyl-04.jpg","https://jbdecorcdm.com/catalog/mat-vinyl-05.jpg","https://jbdecorcdm.com/catalog/mat-vinyl-06.jpg","https://jbdecorcdm.com/catalog/mat-vinyl-07.jpg","https://jbdecorcdm.com/catalog/mat-vinyl-08.jpg"]',
  '[{"label":"Category","value":"Mats & Flooring"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"MAT-VINYL"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'vinyl-flooring');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Carpets', 'carpets', 'MAT-CARPET',
  (SELECT id FROM shop_categories WHERE slug = 'mats-flooring' AND is_deleted = b'0' LIMIT 1),
  'Wall-to-wall and area carpets for homes, offices and events.', 'Wall-to-wall and area carpets for homes, offices and events.', 'https://jbdecorcdm.com/catalog/mat-carpet-01.jpg', '["https://jbdecorcdm.com/catalog/mat-carpet-01.jpg","https://jbdecorcdm.com/catalog/mat-carpet-02.jpg","https://jbdecorcdm.com/catalog/mat-carpet-03.jpg","https://jbdecorcdm.com/catalog/mat-carpet-04.jpg","https://jbdecorcdm.com/catalog/mat-carpet-05.jpg","https://jbdecorcdm.com/catalog/mat-carpet-06.jpg"]',
  '[{"label":"Category","value":"Mats & Flooring"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"MAT-CARPET"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'carpets');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Artificial Grass Mat', 'artificial-grass-mat', 'MAT-GRASS',
  (SELECT id FROM shop_categories WHERE slug = 'mats-flooring' AND is_deleted = b'0' LIMIT 1),
  'Lush artificial grass for balconies, terraces, play areas and events.', 'Lush artificial grass for balconies, terraces, play areas and events.', 'https://jbdecorcdm.com/catalog/mat-grass-01.jpg', '["https://jbdecorcdm.com/catalog/mat-grass-01.jpg","https://jbdecorcdm.com/catalog/mat-grass-02.jpg","https://jbdecorcdm.com/catalog/mat-grass-03.jpg","https://jbdecorcdm.com/catalog/mat-grass-04.jpg","https://jbdecorcdm.com/catalog/mat-grass-05.jpg","https://jbdecorcdm.com/catalog/mat-grass-06.jpg"]',
  '[{"label":"Category","value":"Mats & Flooring"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"MAT-GRASS"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'artificial-grass-mat');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Foot Mats', 'foot-mats', 'MAT-FOOT',
  (SELECT id FROM shop_categories WHERE slug = 'mats-flooring' AND is_deleted = b'0' LIMIT 1),
  'Doormats and foot mats in coir, rubber and designer prints.', 'Doormats and foot mats in coir, rubber and designer prints.', 'https://jbdecorcdm.com/catalog/mat-foot-01.jpg', '["https://jbdecorcdm.com/catalog/mat-foot-01.jpg","https://jbdecorcdm.com/catalog/mat-foot-02.jpg","https://jbdecorcdm.com/catalog/mat-foot-03.jpg","https://jbdecorcdm.com/catalog/mat-foot-04.jpg","https://jbdecorcdm.com/catalog/mat-foot-05.jpg","https://jbdecorcdm.com/catalog/mat-foot-06.jpg","https://jbdecorcdm.com/catalog/mat-foot-07.jpg","https://jbdecorcdm.com/catalog/mat-foot-08.jpg"]',
  '[{"label":"Category","value":"Mats & Flooring"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"MAT-FOOT"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'foot-mats');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Multi-Purpose Mats', 'multi-purpose-mats', 'MAT-MULTI',
  (SELECT id FROM shop_categories WHERE slug = 'mats-flooring' AND is_deleted = b'0' LIMIT 1),
  'Versatile mats for dining, yoga, kitchens and floors.', 'Versatile mats for dining, yoga, kitchens and floors.', 'https://jbdecorcdm.com/catalog/mat-multi-01.jpg', '["https://jbdecorcdm.com/catalog/mat-multi-01.jpg","https://jbdecorcdm.com/catalog/mat-multi-02.jpg","https://jbdecorcdm.com/catalog/mat-multi-03.jpg","https://jbdecorcdm.com/catalog/mat-multi-04.jpg","https://jbdecorcdm.com/catalog/mat-multi-05.jpg","https://jbdecorcdm.com/catalog/mat-multi-06.jpg","https://jbdecorcdm.com/catalog/mat-multi-07.jpg","https://jbdecorcdm.com/catalog/mat-multi-08.jpg","https://jbdecorcdm.com/catalog/mat-multi-09.jpg","https://jbdecorcdm.com/catalog/mat-multi-10.jpg"]',
  '[{"label":"Category","value":"Mats & Flooring"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"MAT-MULTI"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'multi-purpose-mats');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Wall Sticker Rolls', 'wall-sticker-rolls', 'WALL-STICKER',
  (SELECT id FROM shop_categories WHERE slug = 'wall-decor' AND is_deleted = b'0' LIMIT 1),
  'Self-adhesive decorative wall sticker rolls for a quick makeover.', 'Self-adhesive decorative wall sticker rolls for a quick makeover.', 'https://jbdecorcdm.com/catalog/wall-sticker-01.jpg', '["https://jbdecorcdm.com/catalog/wall-sticker-01.jpg","https://jbdecorcdm.com/catalog/wall-sticker-02.jpg","https://jbdecorcdm.com/catalog/wall-sticker-03.jpg","https://jbdecorcdm.com/catalog/wall-sticker-04.jpg","https://jbdecorcdm.com/catalog/wall-sticker-05.jpg","https://jbdecorcdm.com/catalog/wall-sticker-06.jpg","https://jbdecorcdm.com/catalog/wall-sticker-07.jpg"]',
  '[{"label":"Category","value":"Wall Decor"},{"label":"Sold by","value":"roll"},{"label":"Product code","value":"WALL-STICKER"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'wall-sticker-rolls');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Wallpapers', 'wallpapers', 'WALL-PAPER',
  (SELECT id FROM shop_categories WHERE slug = 'wall-decor' AND is_deleted = b'0' LIMIT 1),
  'Designer wallpapers in textured, 3D, floral and modern patterns.', 'Designer wallpapers in textured, 3D, floral and modern patterns.', 'https://jbdecorcdm.com/catalog/wall-paper-01.jpg', '["https://jbdecorcdm.com/catalog/wall-paper-01.jpg","https://jbdecorcdm.com/catalog/wall-paper-02.jpg","https://jbdecorcdm.com/catalog/wall-paper-03.jpg","https://jbdecorcdm.com/catalog/wall-paper-04.jpg","https://jbdecorcdm.com/catalog/wall-paper-05.jpg","https://jbdecorcdm.com/catalog/wall-paper-06.jpg"]',
  '[{"label":"Category","value":"Wall Decor"},{"label":"Sold by","value":"roll"},{"label":"Product code","value":"WALL-PAPER"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'wallpapers');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Wall Fluted Panels', 'wall-fluted-panels', 'WALL-FLUTED',
  (SELECT id FROM shop_categories WHERE slug = 'wall-decor' AND is_deleted = b'0' LIMIT 1),
  'WPC/PVC fluted wall panels for feature walls, TV backdrops and headboards.', 'WPC/PVC fluted wall panels for feature walls, TV backdrops and headboards.', 'https://jbdecorcdm.com/catalog/wall-fluted-01.jpg', '["https://jbdecorcdm.com/catalog/wall-fluted-01.jpg","https://jbdecorcdm.com/catalog/wall-fluted-02.jpg","https://jbdecorcdm.com/catalog/wall-fluted-03.jpg","https://jbdecorcdm.com/catalog/wall-fluted-04.jpg","https://jbdecorcdm.com/catalog/wall-fluted-05.jpg"]',
  '[{"label":"Category","value":"Wall Decor"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"WALL-FLUTED"}]', 0, 0, 0, 0, b'1', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'wall-fluted-panels');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Wall UV Sheets', 'wall-uv-sheets', 'WALL-UV',
  (SELECT id FROM shop_categories WHERE slug = 'wall-decor' AND is_deleted = b'0' LIMIT 1),
  'High-gloss UV marble sheets, a lightweight alternative to stone for walls.', 'High-gloss UV marble sheets, a lightweight alternative to stone for walls.', 'https://jbdecorcdm.com/catalog/wall-uv-01.jpg', '["https://jbdecorcdm.com/catalog/wall-uv-01.jpg","https://jbdecorcdm.com/catalog/wall-uv-02.jpg","https://jbdecorcdm.com/catalog/wall-uv-03.jpg","https://jbdecorcdm.com/catalog/wall-uv-04.jpg"]',
  '[{"label":"Category","value":"Wall Decor"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"WALL-UV"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'wall-uv-sheets');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Wall Foam Sheets', 'wall-foam-sheets', 'WALL-FOAM',
  (SELECT id FROM shop_categories WHERE slug = 'wall-decor' AND is_deleted = b'0' LIMIT 1),
  '3D self-adhesive foam wall panels. Soft, insulating and easy to install.', '3D self-adhesive foam wall panels. Soft, insulating and easy to install.', 'https://jbdecorcdm.com/catalog/wall-foam-01.jpg', '["https://jbdecorcdm.com/catalog/wall-foam-01.jpg","https://jbdecorcdm.com/catalog/wall-foam-02.jpg","https://jbdecorcdm.com/catalog/wall-foam-03.jpg","https://jbdecorcdm.com/catalog/wall-foam-04.jpg"]',
  '[{"label":"Category","value":"Wall Decor"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"WALL-FOAM"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'wall-foam-sheets');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Modular Kitchen', 'modular-kitchen', 'INT-KITCHEN',
  (SELECT id FROM shop_categories WHERE slug = 'interior-works' AND is_deleted = b'0' LIMIT 1),
  'Custom modular kitchens in L, U, parallel and straight layouts with premium finishes and fittings.', 'Custom modular kitchens in L, U, parallel and straight layouts with premium finishes and fittings.', 'https://jbdecorcdm.com/catalog/int-kitchen-01.jpg', '["https://jbdecorcdm.com/catalog/int-kitchen-01.jpg","https://jbdecorcdm.com/catalog/int-kitchen-02.jpg","https://jbdecorcdm.com/catalog/int-kitchen-03.jpg","https://jbdecorcdm.com/catalog/int-kitchen-04.jpg","https://jbdecorcdm.com/catalog/int-kitchen-05.jpg","https://jbdecorcdm.com/catalog/int-kitchen-06.jpg","https://jbdecorcdm.com/catalog/int-kitchen-07.jpg","https://jbdecorcdm.com/catalog/int-kitchen-08.jpg","https://jbdecorcdm.com/catalog/int-kitchen-09.jpg","https://jbdecorcdm.com/catalog/int-kitchen-10.jpg"]',
  '[{"label":"Category","value":"Interior Works"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"INT-KITCHEN"}]', 0, 0, 0, 0, b'1', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'modular-kitchen');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Wardrobes', 'wardrobes', 'INT-WARDROBE',
  (SELECT id FROM shop_categories WHERE slug = 'interior-works' AND is_deleted = b'0' LIMIT 1),
  'Sliding and hinged wardrobes built to fit your space, with lofts, drawers and mirror options.', 'Sliding and hinged wardrobes built to fit your space, with lofts, drawers and mirror options.', 'https://jbdecorcdm.com/catalog/int-wardrobe-01.jpg', '["https://jbdecorcdm.com/catalog/int-wardrobe-01.jpg","https://jbdecorcdm.com/catalog/int-wardrobe-02.jpg","https://jbdecorcdm.com/catalog/int-wardrobe-03.jpg","https://jbdecorcdm.com/catalog/int-wardrobe-04.jpg","https://jbdecorcdm.com/catalog/int-wardrobe-05.jpg","https://jbdecorcdm.com/catalog/int-wardrobe-06.jpg","https://jbdecorcdm.com/catalog/int-wardrobe-07.jpg","https://jbdecorcdm.com/catalog/int-wardrobe-08.jpg","https://jbdecorcdm.com/catalog/int-wardrobe-09.jpg","https://jbdecorcdm.com/catalog/int-wardrobe-10.jpg"]',
  '[{"label":"Category","value":"Interior Works"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"INT-WARDROBE"}]', 0, 0, 0, 0, b'1', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'wardrobes');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'PVC Cupboards', 'pvc-cupboards', 'INT-PVC',
  (SELECT id FROM shop_categories WHERE slug = 'interior-works' AND is_deleted = b'0' LIMIT 1),
  'Waterproof, termite-proof PVC cupboards for kitchens, bathrooms and utility areas.', 'Waterproof, termite-proof PVC cupboards for kitchens, bathrooms and utility areas.', 'https://jbdecorcdm.com/catalog/int-pvc-01.jpg', '["https://jbdecorcdm.com/catalog/int-pvc-01.jpg","https://jbdecorcdm.com/catalog/int-pvc-02.jpg","https://jbdecorcdm.com/catalog/int-pvc-03.jpg","https://jbdecorcdm.com/catalog/int-pvc-04.jpg","https://jbdecorcdm.com/catalog/int-pvc-05.jpg","https://jbdecorcdm.com/catalog/int-pvc-06.jpg","https://jbdecorcdm.com/catalog/int-pvc-07.jpg","https://jbdecorcdm.com/catalog/int-pvc-08.jpg","https://jbdecorcdm.com/catalog/int-pvc-09.jpg","https://jbdecorcdm.com/catalog/int-pvc-10.jpg"]',
  '[{"label":"Category","value":"Interior Works"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"INT-PVC"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'pvc-cupboards');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'uPVC Cupboards', 'upvc-cupboards', 'INT-UPVC',
  (SELECT id FROM shop_categories WHERE slug = 'interior-works' AND is_deleted = b'0' LIMIT 1),
  'Strong, low-maintenance uPVC cupboards and storage units.', 'Strong, low-maintenance uPVC cupboards and storage units.', 'https://jbdecorcdm.com/catalog/int-upvc-01.jpg', '["https://jbdecorcdm.com/catalog/int-upvc-01.jpg","https://jbdecorcdm.com/catalog/int-upvc-02.jpg","https://jbdecorcdm.com/catalog/int-upvc-03.jpg","https://jbdecorcdm.com/catalog/int-upvc-04.jpg","https://jbdecorcdm.com/catalog/int-upvc-05.jpg"]',
  '[{"label":"Category","value":"Interior Works"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"INT-UPVC"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'upvc-cupboards');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Aluminium Works', 'aluminium-works', 'INT-ALU',
  (SELECT id FROM shop_categories WHERE slug = 'interior-works' AND is_deleted = b'0' LIMIT 1),
  'Aluminium partitions, windows, doors and cupboards.', 'Aluminium partitions, windows, doors and cupboards.', 'https://jbdecorcdm.com/catalog/int-alu-01.jpg', '["https://jbdecorcdm.com/catalog/int-alu-01.jpg","https://jbdecorcdm.com/catalog/int-alu-02.jpg","https://jbdecorcdm.com/catalog/int-alu-03.jpg","https://jbdecorcdm.com/catalog/int-alu-04.jpg","https://jbdecorcdm.com/catalog/int-alu-05.jpg","https://jbdecorcdm.com/catalog/int-alu-06.jpg","https://jbdecorcdm.com/catalog/int-alu-07.jpg","https://jbdecorcdm.com/catalog/int-alu-08.jpg"]',
  '[{"label":"Category","value":"Interior Works"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"INT-ALU"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'aluminium-works');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'False Ceiling', 'false-ceiling', 'INT-CEILING',
  (SELECT id FROM shop_categories WHERE slug = 'interior-works' AND is_deleted = b'0' LIMIT 1),
  'Gypsum and PVC false ceilings with cove lighting and modern designs.', 'Gypsum and PVC false ceilings with cove lighting and modern designs.', 'https://jbdecorcdm.com/catalog/int-ceiling-01.jpg', '["https://jbdecorcdm.com/catalog/int-ceiling-01.jpg","https://jbdecorcdm.com/catalog/int-ceiling-02.jpg","https://jbdecorcdm.com/catalog/int-ceiling-03.jpg","https://jbdecorcdm.com/catalog/int-ceiling-04.jpg","https://jbdecorcdm.com/catalog/int-ceiling-05.jpg","https://jbdecorcdm.com/catalog/int-ceiling-06.jpg","https://jbdecorcdm.com/catalog/int-ceiling-07.jpg","https://jbdecorcdm.com/catalog/int-ceiling-08.jpg","https://jbdecorcdm.com/catalog/int-ceiling-09.jpg"]',
  '[{"label":"Category","value":"Interior Works"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"INT-CEILING"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'false-ceiling');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Shop Interiors', 'shop-interiors', 'INT-SHOP',
  (SELECT id FROM shop_categories WHERE slug = 'interior-works' AND is_deleted = b'0' LIMIT 1),
  'Shop fit-outs including racks, display units and counters for retail stores.', 'Shop fit-outs including racks, display units and counters for retail stores.', 'https://jbdecorcdm.com/catalog/int-shop-01.jpg', '["https://jbdecorcdm.com/catalog/int-shop-01.jpg","https://jbdecorcdm.com/catalog/int-shop-02.jpg","https://jbdecorcdm.com/catalog/int-shop-03.jpg","https://jbdecorcdm.com/catalog/int-shop-04.jpg","https://jbdecorcdm.com/catalog/int-shop-05.jpg","https://jbdecorcdm.com/catalog/int-shop-06.jpg","https://jbdecorcdm.com/catalog/int-shop-07.jpg","https://jbdecorcdm.com/catalog/int-shop-08.jpg","https://jbdecorcdm.com/catalog/int-shop-09.jpg","https://jbdecorcdm.com/catalog/int-shop-10.jpg"]',
  '[{"label":"Category","value":"Interior Works"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"INT-SHOP"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'shop-interiors');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'TV Units', 'tv-units', 'INT-TV',
  (SELECT id FROM shop_categories WHERE slug = 'interior-works' AND is_deleted = b'0' LIMIT 1),
  'Custom TV units and entertainment walls with storage, panelling and lighting.', 'Custom TV units and entertainment walls with storage, panelling and lighting.', 'https://jbdecorcdm.com/catalog/int-tv-01.jpg', '["https://jbdecorcdm.com/catalog/int-tv-01.jpg","https://jbdecorcdm.com/catalog/int-tv-02.jpg","https://jbdecorcdm.com/catalog/int-tv-03.jpg","https://jbdecorcdm.com/catalog/int-tv-04.jpg","https://jbdecorcdm.com/catalog/int-tv-05.jpg","https://jbdecorcdm.com/catalog/int-tv-06.jpg","https://jbdecorcdm.com/catalog/int-tv-07.jpg","https://jbdecorcdm.com/catalog/int-tv-08.jpg","https://jbdecorcdm.com/catalog/int-tv-09.jpg","https://jbdecorcdm.com/catalog/int-tv-10.jpg"]',
  '[{"label":"Category","value":"Interior Works"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"INT-TV"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'tv-units');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Wall Shelves', 'wall-shelves', 'INT-SHELF',
  (SELECT id FROM shop_categories WHERE slug = 'interior-works' AND is_deleted = b'0' LIMIT 1),
  'Floating and decorative wall shelves for living rooms, bedrooms and pooja rooms.', 'Floating and decorative wall shelves for living rooms, bedrooms and pooja rooms.', 'https://jbdecorcdm.com/catalog/int-shelf-01.jpg', '["https://jbdecorcdm.com/catalog/int-shelf-01.jpg","https://jbdecorcdm.com/catalog/int-shelf-02.jpg","https://jbdecorcdm.com/catalog/int-shelf-03.jpg","https://jbdecorcdm.com/catalog/int-shelf-04.jpg","https://jbdecorcdm.com/catalog/int-shelf-05.jpg","https://jbdecorcdm.com/catalog/int-shelf-06.jpg","https://jbdecorcdm.com/catalog/int-shelf-07.jpg","https://jbdecorcdm.com/catalog/int-shelf-08.jpg","https://jbdecorcdm.com/catalog/int-shelf-09.jpg","https://jbdecorcdm.com/catalog/int-shelf-10.jpg"]',
  '[{"label":"Category","value":"Interior Works"},{"label":"Sold by","value":"sqft"},{"label":"Product code","value":"INT-SHELF"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'wall-shelves');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Beads Curtains', 'beads-curtains', 'DEC-BEADS',
  (SELECT id FROM shop_categories WHERE slug = 'home-decor' AND is_deleted = b'0' LIMIT 1),
  'Decorative bead curtains for doorways, partitions and pooja rooms.', 'Decorative bead curtains for doorways, partitions and pooja rooms.', 'https://jbdecorcdm.com/catalog/dec-beads-01.jpg', '["https://jbdecorcdm.com/catalog/dec-beads-01.jpg","https://jbdecorcdm.com/catalog/dec-beads-02.jpg","https://jbdecorcdm.com/catalog/dec-beads-03.jpg"]',
  '[{"label":"Category","value":"Home Decor"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"DEC-BEADS"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'beads-curtains');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Crystal Curtains', 'crystal-curtains', 'DEC-CRYSTAL',
  (SELECT id FROM shop_categories WHERE slug = 'home-decor' AND is_deleted = b'0' LIMIT 1),
  'Sparkling crystal string curtains for doorways, partitions and events.', 'Sparkling crystal string curtains for doorways, partitions and events.', 'https://jbdecorcdm.com/catalog/dec-crystal-01.jpg', '["https://jbdecorcdm.com/catalog/dec-crystal-01.jpg","https://jbdecorcdm.com/catalog/dec-crystal-02.jpg","https://jbdecorcdm.com/catalog/dec-crystal-03.jpg"]',
  '[{"label":"Category","value":"Home Decor"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"DEC-CRYSTAL"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'crystal-curtains');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Thread Curtains', 'thread-curtains', 'DEC-THREAD',
  (SELECT id FROM shop_categories WHERE slug = 'home-decor' AND is_deleted = b'0' LIMIT 1),
  'Light, flowing thread (string) curtains for doorways and room partitions.', 'Light, flowing thread (string) curtains for doorways and room partitions.', 'https://jbdecorcdm.com/catalog/dec-thread-01.jpg', '["https://jbdecorcdm.com/catalog/dec-thread-01.jpg"]',
  '[{"label":"Category","value":"Home Decor"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"DEC-THREAD"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'thread-curtains');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Mani Curtains', 'mani-curtains', 'DEC-MANI',
  (SELECT id FROM shop_categories WHERE slug = 'home-decor' AND is_deleted = b'0' LIMIT 1),
  'Traditional mani (bead-string) curtains for doorways and pooja rooms.', 'Traditional mani (bead-string) curtains for doorways and pooja rooms.', NULL, NULL,
  '[{"label":"Category","value":"Home Decor"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"DEC-MANI"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'mani-curtains');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Curtain Lace', 'curtain-lace', 'DEC-LACE',
  (SELECT id FROM shop_categories WHERE slug = 'home-decor' AND is_deleted = b'0' LIMIT 1),
  'Decorative tassel laces and borders to finish curtains, valances and cushions.', 'Decorative tassel laces and borders to finish curtains, valances and cushions.', 'https://jbdecorcdm.com/catalog/dec-lace-01.jpg', '["https://jbdecorcdm.com/catalog/dec-lace-01.jpg","https://jbdecorcdm.com/catalog/dec-lace-02.jpg","https://jbdecorcdm.com/catalog/dec-lace-03.jpg"]',
  '[{"label":"Category","value":"Home Decor"},{"label":"Sold by","value":"meter"},{"label":"Product code","value":"DEC-LACE"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'curtain-lace');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Curtain Tassels & Tie-Backs', 'curtain-tassels-tie-backs', 'DEC-TASSEL',
  (SELECT id FROM shop_categories WHERE slug = 'home-decor' AND is_deleted = b'0' LIMIT 1),
  'Decorative tassel tie-backs to hold curtains open in style.', 'Decorative tassel tie-backs to hold curtains open in style.', 'https://jbdecorcdm.com/catalog/dec-tassel-01.jpg', '["https://jbdecorcdm.com/catalog/dec-tassel-01.jpg","https://jbdecorcdm.com/catalog/dec-tassel-02.jpg","https://jbdecorcdm.com/catalog/dec-tassel-03.jpg","https://jbdecorcdm.com/catalog/dec-tassel-04.jpg"]',
  '[{"label":"Category","value":"Home Decor"},{"label":"Sold by","value":"pair"},{"label":"Product code","value":"DEC-TASSEL"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'curtain-tassels-tie-backs');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Bed Covers', 'bed-covers', 'DEC-BEDCOVER',
  (SELECT id FROM shop_categories WHERE slug = 'home-decor' AND is_deleted = b'0' LIMIT 1),
  'Printed bedsheets and bed covers in cotton and quilted fabrics.', 'Printed bedsheets and bed covers in cotton and quilted fabrics.', 'https://jbdecorcdm.com/catalog/dec-bedcover-01.jpg', '["https://jbdecorcdm.com/catalog/dec-bedcover-01.jpg","https://jbdecorcdm.com/catalog/dec-bedcover-02.jpg"]',
  '[{"label":"Category","value":"Home Decor"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"DEC-BEDCOVER"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'bed-covers');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Sofa Covers', 'sofa-covers', 'DEC-SOFACOVER',
  (SELECT id FROM shop_categories WHERE slug = 'home-decor' AND is_deleted = b'0' LIMIT 1),
  'Stretchable and reversible sofa covers and panels that protect and refresh your sofa.', 'Stretchable and reversible sofa covers and panels that protect and refresh your sofa.', 'https://jbdecorcdm.com/catalog/dec-sofacover-01.jpg', '["https://jbdecorcdm.com/catalog/dec-sofacover-01.jpg","https://jbdecorcdm.com/catalog/dec-sofacover-02.jpg","https://jbdecorcdm.com/catalog/dec-sofacover-03.jpg"]',
  '[{"label":"Category","value":"Home Decor"},{"label":"Sold by","value":"set"},{"label":"Product code","value":"DEC-SOFACOVER"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'sofa-covers');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Table Covers', 'table-covers', 'DEC-TABLECOVER',
  (SELECT id FROM shop_categories WHERE slug = 'home-decor' AND is_deleted = b'0' LIMIT 1),
  'Dining table covers and runners in lace, printed and embroidered designs.', 'Dining table covers and runners in lace, printed and embroidered designs.', 'https://jbdecorcdm.com/catalog/dec-tablecover-01.jpg', '["https://jbdecorcdm.com/catalog/dec-tablecover-01.jpg","https://jbdecorcdm.com/catalog/dec-tablecover-02.jpg"]',
  '[{"label":"Category","value":"Home Decor"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"DEC-TABLECOVER"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'table-covers');
INSERT INTO shop_products (created_at, updated_at, created_by, version, is_deleted, name, slug, sku, category_id,
  short_description, description, image_url, gallery_json, specifications_json, price, stock, rating, review_count, featured, active)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Function Table Covers & Skirting', 'function-table-covers-skirting', 'DEC-FUNCTION',
  (SELECT id FROM shop_categories WHERE slug = 'home-decor' AND is_deleted = b'0' LIMIT 1),
  'Table covers and pleated skirting for weddings, functions, events and banquet halls.', 'Table covers and pleated skirting for weddings, functions, events and banquet halls.', 'https://jbdecorcdm.com/catalog/dec-function-01.jpg', '["https://jbdecorcdm.com/catalog/dec-function-01.jpg","https://jbdecorcdm.com/catalog/dec-function-02.jpg","https://jbdecorcdm.com/catalog/dec-function-03.jpg"]',
  '[{"label":"Category","value":"Home Decor"},{"label":"Sold by","value":"pcs"},{"label":"Product code","value":"DEC-FUNCTION"}]', 0, 0, 0, 0, b'0', b'1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM shop_products WHERE slug = 'function-table-covers-skirting');

-- ── Services ──
INSERT INTO services (created_at, updated_at, created_by, version, is_deleted, title, slug, short_description, overview, image_url, icon, active, display_order)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Measurement Service', 'measurement-service', 'Our team visits your site to take accurate measurements for curtains, blinds, nets and interiors.', 'Our team visits your site to take accurate measurements for curtains, blinds, nets and interiors.',
  'https://jbdecorcdm.com/catalog/srv-measure-01.jpg', 'PencilRuler', b'1', 1
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'measurement-service');
INSERT INTO services (created_at, updated_at, created_by, version, is_deleted, title, slug, short_description, overview, image_url, icon, active, display_order)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Tailoring & Stitching', 'tailoring-stitching', 'In-house tailoring and stitching for curtains, cushions and soft furnishings.', 'In-house tailoring and stitching for curtains, cushions and soft furnishings.',
  'https://jbdecorcdm.com/catalog/srv-stitch-01.jpg', 'Gem', b'1', 2
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'tailoring-stitching');
INSERT INTO services (created_at, updated_at, created_by, version, is_deleted, title, slug, short_description, overview, image_url, icon, active, display_order)
SELECT NOW(6), NOW(6), 'catalog-import', 0, b'0', 'Installation & Fitting', 'installation-fitting', 'Professional installation of curtains, rods, blinds, nets and wall decor.', 'Professional installation of curtains, rods, blinds, nets and wall decor.',
  'https://jbdecorcdm.com/catalog/srv-install-01.jpg', 'Wrench', b'1', 3
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM services WHERE slug = 'installation-fitting');
