import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ChevronLeft, ChevronRight, Download, ExternalLink, Pencil, Trash2, X, Crop } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog';
import { resolveFileUrl } from '@/lib/uploadFile';
import { useImageViewer } from '@/components/ImageViewerProvider';
import { toast } from '@/components/ui/toast';
import { FileThumb, SourceChip } from './FileTile';
import { ProjectFile, SOURCES, UPLOAD_TYPES, fmtWhen, projectFilesApi } from './fileTypes';
import AudioPlayer from "@/components/AudioPlayer";
import CallDetails from "@/components/callRecordings/CallDetails";

/**
 * Full-screen viewer: the file itself (photo / PDF / video / voice) with prev-next, and a details panel —
 * what it is, where it came from, who added it — with edit / delete for files uploaded to the project.
 */
export default function FileViewer({ files, index, onIndex, onClose, onChanged, canEdit }: {
  files: ProjectFile[];
  index: number | null;
  onIndex: (i: number) => void;
  onClose: () => void;
  onChanged: () => void;
  canEdit: boolean;
}) {
  const navigate = useNavigate();
  const { openImage } = useImageViewer();
  const file = index != null ? files[index] : null;
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({ fileName: '', documentType: '', remarks: '' });
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    setEditing(false);
    if (file) setForm({ fileName: file.fileName, documentType: file.type, remarks: file.description || '' });
  }, [file?.key]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (index == null) return;
    const onKey = (e: KeyboardEvent) => {
      if ((e.target as HTMLElement)?.tagName === 'INPUT' || (e.target as HTMLElement)?.tagName === 'TEXTAREA') return;
      if (e.key === 'ArrowRight' && index < files.length - 1) onIndex(index + 1);
      if (e.key === 'ArrowLeft' && index > 0) onIndex(index - 1);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [index, files.length, onIndex]);

  if (!file) return null;
  const url = resolveFileUrl(file.fileUrl);
  const editable = canEdit && file.editable && file.docId != null;

  const save = async () => {
    setBusy(true);
    try {
      await projectFilesApi.update(file.docId!, form);
      toast.success('Details saved');
      setEditing(false);
      onChanged();
    } catch { toast.error('Could not save the details'); }
    finally { setBusy(false); }
  };

  const remove = async () => {
    if (!confirm(`Delete "${file.fileName}" from this project?`)) return;
    setBusy(true);
    try {
      await projectFilesApi.remove(file.docId!);
      toast.success('File deleted');
      onClose();
      onChanged();
    } catch { toast.error('Could not delete the file'); }
    finally { setBusy(false); }
  };

  const editImage = () => {
    openImage({
      src: url, fileName: file.fileName, editable: true, module: 'PROJECT',
      onReplace: ({ url: newUrl, fileName }) => {
        projectFilesApi.replaceFile(file.docId!, { fileUrl: newUrl, fileName })
          .then(() => { toast.success('Image updated'); onChanged(); })
          .catch(() => toast.error('Failed to save the edited image.'));
      },
    });
  };

  return (
    <Dialog open onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="flex h-[92vh] max-h-[92vh] w-[96vw] max-w-6xl flex-col gap-0 overflow-hidden p-0 lg:flex-row [&>button]:hidden">
        <DialogTitle className="sr-only">{file.fileName}</DialogTitle>
        {/* Media */}
        <div className="relative flex min-h-0 flex-1 items-center justify-center bg-slate-950">
          {file.kind === 'image' ? (
            <img src={url} alt={file.fileName} className="max-h-full max-w-full object-contain" />
          ) : file.kind === 'pdf' && !file.generated ? (
            <iframe src={url} title={file.fileName} className="h-full w-full bg-white" />
          ) : file.kind === 'video' ? (
            <video src={url} controls className="max-h-full max-w-full" />
          ) : file.kind === 'audio' ? (
            <div className="flex w-full max-w-md flex-col items-center gap-4 p-6">
              <div className="h-40 w-40 overflow-hidden rounded-3xl"><FileThumb kind="audio" /></div>
              <AudioPlayer src={url} className="w-full" autoPlay />
            </div>
          ) : (
            <div className="flex flex-col items-center gap-4 p-6 text-center">
              <div className="h-40 w-40 overflow-hidden rounded-3xl"><FileThumb kind={file.kind} name={file.fileName} /></div>
              <p className="max-w-sm text-sm text-slate-300">
                {file.generated ? 'This document is generated by the CRM — open it to view or print.' : 'No preview for this file type — download or open it.'}
              </p>
              {file.generated ? (
                <button onClick={() => navigate(file.fileUrl)} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-900">
                  <ExternalLink className="h-4 w-4" /> Open {file.type.toLowerCase()}
                </button>
              ) : (
                <a href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-900">
                  <ExternalLink className="h-4 w-4" /> Open file
                </a>
              )}
            </div>
          )}
          {index! > 0 && (
            <button onClick={() => onIndex(index! - 1)} aria-label="Previous"
              className="absolute left-3 top-1/2 flex h-10 w-10 -translate-y-1/2 items-center justify-center rounded-full bg-white/15 text-white backdrop-blur hover:bg-white/25">
              <ChevronLeft className="h-5 w-5" />
            </button>
          )}
          {index! < files.length - 1 && (
            <button onClick={() => onIndex(index! + 1)} aria-label="Next"
              className="absolute right-3 top-1/2 flex h-10 w-10 -translate-y-1/2 items-center justify-center rounded-full bg-white/15 text-white backdrop-blur hover:bg-white/25">
              <ChevronRight className="h-5 w-5" />
            </button>
          )}
          <span className="absolute bottom-3 left-1/2 -translate-x-1/2 rounded-full bg-black/50 px-2.5 py-0.5 text-[11px] text-white">
            {index! + 1} / {files.length}
          </span>
          <button onClick={onClose} aria-label="Close"
            className="absolute right-3 top-3 flex h-9 w-9 items-center justify-center rounded-full bg-white/15 text-white backdrop-blur hover:bg-white/25 lg:hidden">
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Details */}
        <aside className="flex max-h-[42vh] w-full shrink-0 flex-col overflow-y-auto border-t border-slate-200 bg-white lg:max-h-none lg:w-[340px] lg:border-l lg:border-t-0">
          <div className="flex items-start justify-between gap-2 border-b border-slate-100 p-4">
            <div className="min-w-0">
              <p className="text-[11px] font-semibold uppercase tracking-wide text-emerald-700">{file.type}</p>
              <p className="break-words text-[15px] font-semibold text-slate-800">{file.fileName}</p>
            </div>
            <button onClick={onClose} aria-label="Close" className="hidden h-8 w-8 shrink-0 items-center justify-center rounded-full text-slate-400 hover:bg-slate-100 lg:flex">
              <X className="h-4 w-4" />
            </button>
          </div>

          {editing ? (
            <div className="flex flex-col gap-3 p-4">
              <label className="text-[12px] font-medium text-slate-600">Name
                <input value={form.fileName} onChange={(e) => setForm({ ...form, fileName: e.target.value })}
                  className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-emerald-500" />
              </label>
              <label className="text-[12px] font-medium text-slate-600">What is this?
                <select value={form.documentType} onChange={(e) => setForm({ ...form, documentType: e.target.value })}
                  className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-emerald-500">
                  {[...new Set([form.documentType, ...UPLOAD_TYPES])].filter(Boolean).map((t) => <option key={t}>{t}</option>)}
                </select>
              </label>
              <label className="text-[12px] font-medium text-slate-600">About this file
                <textarea value={form.remarks} onChange={(e) => setForm({ ...form, remarks: e.target.value })} rows={3}
                  placeholder="e.g. Signed agreement with the customer"
                  className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-emerald-500" />
              </label>
              <div className="flex gap-2">
                <button onClick={save} disabled={busy} className="flex-1 rounded-lg bg-emerald-700 py-2 text-sm font-semibold text-white disabled:opacity-50">Save</button>
                <button onClick={() => setEditing(false)} className="flex-1 rounded-lg border border-slate-200 py-2 text-sm font-medium text-slate-600">Cancel</button>
              </div>
            </div>
          ) : (
            <dl className="flex flex-col gap-3 p-4 text-[13px]">
              {file.call && (
                <div className="rounded-xl border border-sky-100 bg-sky-50/40 p-3">
                  <p className="mb-2 text-[11px] font-semibold uppercase tracking-wide text-sky-700">Call details</p>
                  <CallDetails call={file.call} />
                </div>
              )}
              {!file.call && <div>
                <dt className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">About</dt>
                <dd className="mt-0.5 whitespace-pre-wrap text-slate-700">{file.description || <span className="text-slate-400">No description</span>}</dd>
              </div>}
              <div>
                <dt className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">From</dt>
                <dd className="mt-1 flex flex-wrap items-center gap-2">
                  <SourceChip file={file} />
                  {file.link && (
                    <button onClick={() => { onClose(); navigate(file.link!); }} className="inline-flex items-center gap-1 text-[12px] font-semibold text-emerald-700 hover:underline">
                      Go there <ExternalLink className="h-3 w-3" />
                    </button>
                  )}
                </dd>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <dt className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">Added by</dt>
                  <dd className="mt-0.5 text-slate-700">{file.addedBy || '—'}</dd>
                </div>
                <div>
                  <dt className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">Date</dt>
                  <dd className="mt-0.5 text-slate-700">{fmtWhen(file.addedAt) || '—'}</dd>
                </div>
              </div>
              {!file.editable && !file.generated && (
                <p className="rounded-lg bg-slate-50 p-2.5 text-[12px] text-slate-500">
                  Added in {(SOURCES[file.source] || 'another module').toLowerCase()} — change or remove it there.
                </p>
              )}
            </dl>
          )}

          <div className="mt-auto flex flex-wrap gap-2 border-t border-slate-100 p-4">
            {!file.generated && (
              <a href={url} target="_blank" rel="noreferrer" download
                className="inline-flex flex-1 items-center justify-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-[13px] font-medium text-slate-700 hover:bg-slate-50">
                <Download className="h-4 w-4" /> Download
              </a>
            )}
            {editable && !editing && (
              <button onClick={() => setEditing(true)} className="inline-flex flex-1 items-center justify-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-[13px] font-medium text-slate-700 hover:bg-slate-50">
                <Pencil className="h-4 w-4" /> Edit details
              </button>
            )}
            {editable && file.kind === 'image' && (
              <button onClick={editImage} className="inline-flex flex-1 items-center justify-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-[13px] font-medium text-slate-700 hover:bg-slate-50">
                <Crop className="h-4 w-4" /> Crop / rotate
              </button>
            )}
            {editable && (
              <button onClick={remove} disabled={busy} className="inline-flex items-center justify-center gap-1.5 rounded-lg px-3 py-2 text-[13px] font-medium text-rose-600 hover:bg-rose-50">
                <Trash2 className="h-4 w-4" /> Delete
              </button>
            )}
          </div>
        </aside>
      </DialogContent>
    </Dialog>
  );
}
